document.getElementById("exportBtn").addEventListener("click", () => {
  const statusEl = document.getElementById("status");
  statusEl.textContent = "Extracting...";
  statusEl.style.color = "#3a3a38";

  chrome.cookies.getAll({ domain: ".youtube.com" }, (cookies) => {
    if (!cookies || cookies.length === 0) {
      statusEl.textContent = "No YouTube cookies found!";
      statusEl.style.color = "#c43d3d";
      return;
    }

    let netscapeFormat = "# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by ReClip Exporter\n\n";

    cookies.forEach(c => {
      const domain = c.domain;
      const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
      const path = c.path;
      const secure = c.secure ? "TRUE" : "FALSE";
      const expiration = c.expirationDate ? Math.floor(c.expirationDate) : 0;
      
      netscapeFormat += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${c.name}\t${c.value}\n`;
    });

    const blob = new Blob([netscapeFormat], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    chrome.downloads.download({
      url: url,
      filename: "cookies.txt",
      saveAs: true
    }, (downloadId) => {
      if (chrome.runtime.lastError) {
        statusEl.textContent = "Download cancelled or failed.";
        statusEl.style.color = "#c43d3d";
      } else {
        statusEl.textContent = "Success! Drop this in ReClip downloads.";
        statusEl.style.color = "#2d8a4e";
      }
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    });
  });
});